# contrib/ specific ruff linter overrides

# root linter settings are defined in the file below
extend = "../pyproject.toml"

extend-ignore = [
    # https://github.com/charliermarsh/ruff#flake8-type-checking-tch
    # This is likely to be a high-touch rule that most contribs don't need to care about.
    "TCH001",
    # https://beta.ruff.rs/docs/rules/#flake8-tidy-imports-tid
    "TID251",  # banned-api - is used to prevent opaque attribute errors caused by missing optional dependencies
    # https://beta.ruff.rs/docs/rules/#flake8-datetimez-dtz
    "DTZ", # TODO: probably want to enable this for contrib as well.
    # https://beta.ruff.rs/docs/rules/#pylint-pl
    "PL", # pylint TODO: enable this for contrib
    # https://beta.ruff.rs/docs/rules/#ruff-specific-rules-ruf
    "RUF013", # implicit-optional - TODO: enable this for contrib
]

[isort]
known-first-party = ["great_expectations", "tests"]
known-third-party = ["dataprofiler", "capitalone_dataprofiler_expectations"]
